Traceback (most recent call last):
  File "/home/cd96/psi4conda/envs/jbook/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/cd96/psi4conda/envs/jbook/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cd96/psi4conda/envs/jbook/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cd96/psi4conda/envs/jbook/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/cd96/psi4conda/envs/jbook/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/cd96/psi4conda/envs/jbook/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/cd96/psi4conda/envs/jbook/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------

sigma_IR=10
sigma_Raman=10
# generating animation archive 

freq_gn_ir, int_gn_ir, int_n_ir , freq_gn_raman, int_gn_raman, int_n_raman= spectra_data(ID, sigma_IR, sigma_Raman)
solids_spectra("readme_solids.txt", freq_gn_ir, int_gn_ir, freq_gn_raman, int_gn_raman)

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 5[0m
[1;32m      2[0m sigma_Raman[38;5;241m=[39m[38;5;241m10[39m
[1;32m      3[0m [38;5;66;03m# generating animation archive [39;00m
[0;32m----> 5[0m freq_gn_ir, int_gn_ir, int_n_ir , freq_gn_raman, int_gn_raman, int_n_raman[38;5;241m=[39m spectra_data([43mID[49m, sigma_IR, sigma_Raman)
[1;32m      6[0m solids_spectra([38;5;124m"[39m[38;5;124mreadme_solids.txt[39m[38;5;124m"[39m, freq_gn_ir, int_gn_ir, freq_gn_raman, int_gn_raman)

[0;31mNameError[0m: name 'ID' is not defined

